sudo: required
language: android
dist: trusty
before_install:
  - chmod +x gradlew
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

#    # Specify at least one system image,
#    # if you need to run emulator(s) during your tests
#    - sys-img-x86-android-28

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_script:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"

script:
  - ./gradlew clean build
  - ./gradlew test
  - ./gradlew assembleRelease --stacktrace

notifications:
  
webhooks: https://outlook.office.com/webhook/becd7648-b3f0-4a5b-8597-93d10ba784ab@4c16deb3-342d-4fca-bcd5-b1429308034c/TravisCI/feffeda7a12246f5a7c4066538d3bb70/e93046d6-9857-4153-8e7f-937760066838